{% set name = "continuedev" %}
{% set version = "0.1.104" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/continuedev-{{ version }}.tar.gz
  sha256: ae5661ae0fb2cdd6dd6d55b1c100421196116f12696d77cc5323d42caae243f5
  patches:
    # Bump directory-tree to 0.0.4
    # Use beautifulsoup4 instead of bs4.
    - dependencies.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - typegen = continuedev.models.generate_json_schema:main


requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.8,<4.0
    - openai >=0.27.5,<0.28.0
    - boltons >=23.0.0,<24.0.0
    - pydantic >=1.10.8,<2.0.0
    - uvicorn >=0.21.1,<0.22.0
    - python-dotenv >=1.0.0,<2.0.0
    - nest-asyncio >=1.5.6,<2.0.0
    - websockets >=11.0.2,<12.0.0
    - urllib3 ==1.26.15
    - posthog >=3.0.1,<4.0.0
    - tiktoken >=0.4.0,<0.5.0
    - jsonref >=1.1.0,<2.0.0
    - jsonschema >=4.17.3,<5.0.0
    - directory-tree >=0.0.4,<0.0.5.0
    - anthropic >=0.3.4,<0.4.0
    - chevron >=0.14.0,<0.15.0
    - psutil >=5.9.5,<6.0.0
    - pygithub >=1.59.0,<2.0.0
    - meilisearch-python-async >=1.4.8,<2.0.0
    - socksio >=1.0.0,<2.0.0
    - ripgrepy >=2.0.0,<3.0.0
    - beautifulsoup4 >=4,<5
    - replicate >=0.11.0,<0.12.0
    - redbaron >=0.9.2,<0.10.0
    - python-lsp-server >=1.7.4,<2.0.0
    - huggingface_hub >=0.16.4,<0.17.0
    - typer >=0.9.0,<0.10.0
    - chromadb >=0.4.12,<0.5.0
    - fastapi ==0.95.2
    - tree_sitter >=0.20.2,<0.21.0
    - tree_sitter_languages >=1.7.0,<2.0.0
    - rich >=13.6.0,<14.0.0
    - python-socketio >=5.10.0,<6.0.0
    - pathspec >=0.11.2,<0.12.0
    - tqdm >=4.66.1,<5.0.0
    - html2text >=2020.1.16,<2021.0.0

test:
  imports:
    - continuedev
  commands:
    - python -m continuedev --help
    - pip check
  requires:
    - pip

about:
  home: https://continue.dev/
  summary: This package contains the Continue server and core classes needed to build your own recipes.
  description: ⏩ Continue is an open-source autopilot for VS Code and JetBrains—the easiest way to code with any LLM
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/continuedev/continue
  doc_url: https://continue.dev/docs/intro

extra:
  recipe-maintainers:
    - sodre
